services:
  ingress-go:
    restart: always
    image: whatwewant/ingress-go:${SERVICE_INGRESS_GO_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_INGRESS_GO_PORT}:${SERVICE_INGRESS_GO_PORT}
    environment:
      PORT: ${SERVICE_INGRESS_GO_PORT}
    volumes:
      - ${SERVICE_CONFIGS}:/etc/ingress
      
networks:
  default:
    external: true
    name: compose-ingress
