services:
  ingress-go:
    restart: always
    image: whatwewant/ingress:${SERVICE_INGRESS_GO_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_INGRESS_GO_PORT}:8080
    env_file:
      - ${SERVICE_CONFIG}
    volumes:
      - ${SERVICE_CONFIGS}:/etc/ingress
      
networks:
  default:
    external: true
    name: compose-ingress
